name: Java Code Checks
on:
  pull_request:
    branches:
      - main

jobs:
  check-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run check style
        uses: dbelyaev/action-checkstyle@v0.7.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          level: error
          workdir: src/main
          checkstyle_version: 10.11.0